version: '3.8'

services:
  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: strongPassword
      MYSQL_DATABASE: cemaco_db
      MYSQL_USER: mainuser
      MYSQL_PASSWORD: strongPassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pstrongPassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: mainuser
      DB_PASSWORD: strongPassword
      DB_NAME: cemaco_db
      PORT: 8001
    ports:
      - "8001:8001"
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8001
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mysql_data: